language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
env:
  - BUNDLE_GEMFILE=Gemfile.rails3
  - BUNDLE_GEMFILE=Gemfile.rails4
matrix:
  allow_failures:
    - rvm: 1.8.7
      env: BUNDLE_GEMFILE=Gemfile.rails4
    - rvm: 1.9.2
      env: BUNDLE_GEMFILE=Gemfile.rails4
install:
  - bundle install
script:
  - rake test
notifications:
  email: false
